name: Update README with my latest coding stats

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: micheaol/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.13d7d9bb-274a-48d3-8c81-ccbd38989dbf }}
          SHOW_MONTHLY: false
          GITHUB_TOKEN: ${{ github.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 }}
          GITHUB_ACTION: ${{ github.action }}
